<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlanIT.BusinessLogic\PlanIT.BusinessLogic.csproj" />
    <ProjectReference Include="..\PlanIT.Infraestructure\PlanIT.Infraestructure.csproj" />
  </ItemGroup>

</Project>
